name: Build & Push Docker Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockertag: ['ubuntu:20.04', 'ubuntu:22.04']
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64/v8
            linux/arm/v7
          build-args: |
            FROM_IMAGE=${{ matrix.dockertag }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.dockertag }}
